/**
 * TOC (table of contents) extraction for MDX case study pages.
 *
 * Scans raw MDX content for ATX headings, slugs every heading in document
 * order using github-slugger (matching the algorithm used by rehype-slug),
 * and returns only the H2 entries for the sidebar TOC.
 *
 * Slug drift prevention: by feeding ALL headings (H2, H3, …) into the slugger
 * in document order, duplicate-text headings receive the same incremented
 * suffix that rehype-slug would produce. Returning only H2 entries therefore
 * maps correctly to the rendered anchor IDs in the page.
 *
 * Never imported by client components — server-only utility.
 */

import GithubSlugger from "github-slugger";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TocHeading {
  id: string;
  text: string;
  depth: 2;
}

// ---------------------------------------------------------------------------
// Regex patterns
// ---------------------------------------------------------------------------

// Strips fenced code blocks before scanning so that # inside ``` blocks is
// not misidentified as a heading (e.g. `# some comment` in a bash snippet).
const CODE_FENCE_RE = /^```[\s\S]*?^```/gm;

// Matches ATX headings of depth 2–6. Group 1: hashes, Group 2: heading text.
// Depth 1 is excluded — the page template owns <h1> and MDX authors must not
// use # at the top level.
const HEADING_RE = /^(#{2,6})\s+(.+?)(?:\s+#+)?\s*$/gm;

// Strips inline markdown (bold, italic, inline code, links) from heading text
// so the TOC displays clean labels.
const INLINE_MARKUP_RE = /`[^`]*`|\[([^\]]+)\]\([^)]+\)|\*{1,3}([^*]+)\*{1,3}|_{1,3}([^_]+)_{1,3}/g;

function stripInlineMarkup(text: string): string {
  return text
    .replace(
      INLINE_MARKUP_RE,
      (
        _match: string,
        linkText?: string,
        boldItalic?: string,
        underscoreItalic?: string,
      ): string => {
        // Prefer the captured text content over the raw markdown.
        return linkText ?? boldItalic ?? underscoreItalic ?? "";
      },
    )
    .trim();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns TOC entries for all H2 headings found in `content`.
 *
 * Slug IDs are generated by processing every heading in document order so
 * they match the IDs rehype-slug attaches to the rendered HTML.
 *
 * Returns an empty array when the content has fewer than 2 H2 headings —
 * the layout component uses this to decide whether to render the sidebar.
 */
export function extractTocHeadings(content: string): TocHeading[] {
  const slugger = new GithubSlugger();

  // Strip code fences to avoid false positives.
  const stripped = content.replace(CODE_FENCE_RE, "");

  const h2Entries: TocHeading[] = [];

  for (const match of stripped.matchAll(HEADING_RE)) {
    const hashes = match[1];
    const rawText = match[2];
    const depth = hashes.length;
    const cleanText = stripInlineMarkup(rawText);
    // Slug every heading in order so the slugger's duplicate counter stays
    // aligned with rehype-slug's output.
    const id = slugger.slug(cleanText);

    if (depth === 2) {
      h2Entries.push({ id, text: cleanText, depth: 2 });
    }
  }

  return h2Entries;
}
