// Auto-generated by: npm run gen:types
// Source: supabase gen types typescript --local --schema public
// DO NOT EDIT MANUALLY — run `npm run gen:types` to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      accounts: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          plan: "free" | "starter" | "pro";
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          plan?: "free" | "starter" | "pro";
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          plan?: "free" | "starter" | "pro";
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "accounts_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      account_members: {
        Row: {
          id: string;
          account_id: string;
          user_id: string;
          role: "admin" | "member" | "viewer";
          invited_at: string;
          joined_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          user_id: string;
          role: "admin" | "member" | "viewer";
          invited_at?: string;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          user_id?: string;
          role?: "admin" | "member" | "viewer";
          invited_at?: string;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "account_members_account_id_fkey";
            columns: ["account_id"];
            isOneToOne: false;
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "account_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      projects: {
        Row: {
          id: string;
          account_id: string;
          owner_id: string | null;
          name: string;
          description: string | null;
          current_phase: "discovery" | "research" | "design" | "validation" | "delivery";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          owner_id?: string | null;
          name: string;
          description?: string | null;
          current_phase?: "discovery" | "research" | "design" | "validation" | "delivery";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          owner_id?: string | null;
          name?: string;
          description?: string | null;
          current_phase?: "discovery" | "research" | "design" | "validation" | "delivery";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_account_id_fkey";
            columns: ["account_id"];
            isOneToOne: false;
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      milestones: {
        Row: {
          id: string;
          project_id: string;
          account_id: string;
          name: string;
          description: string | null;
          due_at: string | null;
          status: "upcoming" | "in_progress" | "done";
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          account_id?: string;
          name: string;
          description?: string | null;
          due_at?: string | null;
          status?: "upcoming" | "in_progress" | "done";
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          account_id?: string;
          name?: string;
          description?: string | null;
          due_at?: string | null;
          status?: "upcoming" | "in_progress" | "done";
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "milestones_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      deliverables: {
        Row: {
          id: string;
          milestone_id: string;
          account_id: string;
          type: "file" | "link";
          title: string;
          file_path: string | null;
          external_link: string | null;
          status: "draft" | "published" | "approved" | "rejected";
          uploaded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          milestone_id: string;
          account_id?: string;
          type: "file" | "link";
          title: string;
          file_path?: string | null;
          external_link?: string | null;
          status?: "draft" | "published" | "approved" | "rejected";
          uploaded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          milestone_id?: string;
          account_id?: string;
          type?: "file" | "link";
          title?: string;
          file_path?: string | null;
          external_link?: string | null;
          status?: "draft" | "published" | "approved" | "rejected";
          uploaded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deliverables_milestone_id_fkey";
            columns: ["milestone_id"];
            isOneToOne: false;
            referencedRelation: "milestones";
            referencedColumns: ["id"];
          },
        ];
      };
      comments: {
        Row: {
          id: string;
          account_id: string;
          milestone_id: string | null;
          deliverable_id: string | null;
          author_id: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id?: string;
          milestone_id?: string | null;
          deliverable_id?: string | null;
          author_id: string;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          milestone_id?: string | null;
          deliverable_id?: string | null;
          author_id?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comments_milestone_id_fkey";
            columns: ["milestone_id"];
            isOneToOne: false;
            referencedRelation: "milestones";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_deliverable_id_fkey";
            columns: ["deliverable_id"];
            isOneToOne: false;
            referencedRelation: "deliverables";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      intake_forms: {
        Row: {
          id: string;
          project_id: string;
          account_id: string;
          schema: Json;
          responses: Json | null;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          account_id?: string;
          schema?: Json;
          responses?: Json | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          account_id?: string;
          schema?: Json;
          responses?: Json | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "intake_forms_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: true;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          company: string | null;
          message: string;
          user_agent: string | null;
          ip_address: string | null;
          notification_status: "pending" | "sent" | "failed";
          notification_error: string | null;
          notified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          company?: string | null;
          message: string;
          user_agent?: string | null;
          ip_address?: string | null;
          notification_status?: "pending" | "sent" | "failed";
          notification_error?: string | null;
          notified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          company?: string | null;
          message?: string;
          user_agent?: string | null;
          ip_address?: string | null;
          notification_status?: "pending" | "sent" | "failed";
          notification_error?: string | null;
          notified_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_account_owner: {
        Args: { p_account_id: string };
        Returns: boolean;
      };
      is_account_member: {
        Args: { p_account_id: string };
        Returns: boolean;
      };
      account_role: {
        Args: { p_account_id: string };
        Returns: string | null;
      };
      is_project_owner: {
        Args: { p_project_id: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// Convenience type aliases

export type Account = Database["public"]["Tables"]["accounts"]["Row"];
export type AccountInsert = Database["public"]["Tables"]["accounts"]["Insert"];
export type AccountUpdate = Database["public"]["Tables"]["accounts"]["Update"];

export type AccountMember = Database["public"]["Tables"]["account_members"]["Row"];
export type AccountMemberInsert = Database["public"]["Tables"]["account_members"]["Insert"];
export type AccountMemberUpdate = Database["public"]["Tables"]["account_members"]["Update"];

export type Project = Database["public"]["Tables"]["projects"]["Row"];
export type ProjectInsert = Database["public"]["Tables"]["projects"]["Insert"];
export type ProjectUpdate = Database["public"]["Tables"]["projects"]["Update"];

export type Milestone = Database["public"]["Tables"]["milestones"]["Row"];
export type MilestoneInsert = Database["public"]["Tables"]["milestones"]["Insert"];
export type MilestoneUpdate = Database["public"]["Tables"]["milestones"]["Update"];

export type Deliverable = Database["public"]["Tables"]["deliverables"]["Row"];
export type DeliverableInsert = Database["public"]["Tables"]["deliverables"]["Insert"];
export type DeliverableUpdate = Database["public"]["Tables"]["deliverables"]["Update"];

export type Comment = Database["public"]["Tables"]["comments"]["Row"];
export type CommentInsert = Database["public"]["Tables"]["comments"]["Insert"];
export type CommentUpdate = Database["public"]["Tables"]["comments"]["Update"];

export type IntakeForm = Database["public"]["Tables"]["intake_forms"]["Row"];
export type IntakeFormInsert = Database["public"]["Tables"]["intake_forms"]["Insert"];
export type IntakeFormUpdate = Database["public"]["Tables"]["intake_forms"]["Update"];

export type ContactSubmission = Database["public"]["Tables"]["contact_submissions"]["Row"];
export type ContactSubmissionInsert = Database["public"]["Tables"]["contact_submissions"]["Insert"];
export type ContactSubmissionUpdate = Database["public"]["Tables"]["contact_submissions"]["Update"];
